'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveConfig: (cfg) => ipcRenderer.invoke('save-config', cfg),
  pickDir: () => ipcRenderer.invoke('pick-dir'),
  openGameDir: () => ipcRenderer.invoke('open-game-dir'),
  launch: (opts) => ipcRenderer.invoke('launch-game', opts),
  msLogin: () => ipcRenderer.invoke('ms-login'),
  offlineLogin: (name) => ipcRenderer.invoke('offline-login', name),
  logout: () => ipcRenderer.invoke('logout'),
  modsList: (type, loader) => ipcRenderer.invoke('mods-list', { type, loader }),
  modsSearch: (query, type, loader) => ipcRenderer.invoke('mods-search', { query, type, loader }),
  modsPopular: (type, loader) => ipcRenderer.invoke('mods-popular', { type, loader }),
  modDetails: (idOrSlug) => ipcRenderer.invoke('mod-details', { idOrSlug }),
  communityVote: (project, value) => ipcRenderer.invoke('community-vote', { project, value }),
  communityRatings: (ids) => ipcRenderer.invoke('community-ratings', { ids }),
  communityTop: (type) => ipcRenderer.invoke('community-top', { type }),
  buildShare: (loader, parts) => ipcRenderer.invoke('build-share', { loader, parts }),
  buildPreview: (code) => ipcRenderer.invoke('build-preview', { code }),
  buildApply: (code, parts) => ipcRenderer.invoke('build-apply', { code, parts }),
  modInstall: (project, type, loader) => ipcRenderer.invoke('mod-install', { project, type, loader }),
  modToggle: (type, fileName, enabled, bundled) => ipcRenderer.invoke('mod-toggle', { type, fileName, enabled, bundled }),
  modRemove: (type, fileName) => ipcRenderer.invoke('mod-remove', { type, fileName }),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  migrateScan: () => ipcRenderer.invoke('migrate-scan'),
  migratePick: () => ipcRenderer.invoke('migrate-pick'),
  migrateRun: (dir, parts) => ipcRenderer.invoke('migrate-run', { dir, parts }),
  minimize: () => ipcRenderer.send('window-min'),
  close: () => ipcRenderer.send('window-close'),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, d) => cb(d)),
  onStatus: (cb) => ipcRenderer.on('status', (_e, d) => cb(d)),
  onLog: (cb) => ipcRenderer.on('log', (_e, d) => cb(d)),
  onState: (cb) => ipcRenderer.on('state', (_e, d) => cb(d)),
  onLaunchError: (cb) => ipcRenderer.on('launch-error', (_e, d) => cb(d)),
  onAuthExpired: (cb) => ipcRenderer.on('auth-expired', () => cb()),
  onUpdateState: (cb) => ipcRenderer.on('update-state', (_e, d) => cb(d)),
  updateRestart: () => ipcRenderer.send('update-restart'),
});
